// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl8-OVqh1ePxEB7Mp2k5TdlUvZ199yj6w',
    appId: '1:905554908150:web:2ec8768851f9343d56add7',
    messagingSenderId: '905554908150',
    projectId: 'noisy-app-93551',
    authDomain: 'noisy-app-93551.firebaseapp.com',
    storageBucket: 'noisy-app-93551.firebasestorage.app',
    measurementId: 'G-9RLQT9B216',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOpeu1-_F5YY0r2CrNP1fRnVPo1cNcgAA',
    appId: '1:905554908150:android:eb37436b180c2e7a56add7',
    messagingSenderId: '905554908150',
    projectId: 'noisy-app-93551',
    storageBucket: 'noisy-app-93551.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYbs-ensAY193xtYQaXI22Z_AjrSn2-g8',
    appId: '1:905554908150:ios:44ad2456d3fc0a0256add7',
    messagingSenderId: '905554908150',
    projectId: 'noisy-app-93551',
    storageBucket: 'noisy-app-93551.firebasestorage.app',
    iosBundleId: 'com.example.noisyApp',
  );
}
